url: "http://slackshop.ru"
descriptor1: "Команда"
descriptor2: "проводит курс"
email: zor667@gmail.com #TODO #yourname@inbox.ru
vk: https://vk.com/orl1kov
phone: "+7 903 780-35-25"

# Build settings
markdown: kramdown

collections:
  courses:
    output: true
    permalink: /:path/
  course_reviews:
    output: true
  

defaults:
  - scope:
      path: ""
      type: courses
    values:
      layout: course
