url: "http://slackshop.ru"
descriptor: "Производим и продаём слэклайны, <br>учим по ним ходить"
email: mail@mail.ru #TODO #yourname@inbox.ru
vk: https://vk.com/orl1kov

# Build settings
markdown: kramdown

collections:
  courses:
    output: true
    permalink: /:path/
  course_reviews:
    output: true
  

defaults:
  - scope:
      path: ""
      type: courses
    values:
      layout: course
